import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./component/Header";
import { Footer } from "./component/Footer";
import { cookies } from "next/headers";
import { AuthProvider } from "./context/Authcontext";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value || null;
  return (
    <html lang="en">
      <body className="bg-gradient-to-br from-indigo-50 to-white animate-fade-in">
        <Toaster position="top-right" reverseOrder={false} />
        <AuthProvider initialAuth={!!token}>
          <Header />
          <div style={{ height: '100vh' }}>
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
